/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as _dashboardRouteImport } from './routes/__dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as _dashboardSettingsRouteImport } from './routes/__dashboard/settings'
import { Route as _dashboardLogsRouteImport } from './routes/__dashboard/logs'
import { Route as _dashboardDemoRouteImport } from './routes/__dashboard/demo'
import { Route as _dashboardAnalyticsRouteImport } from './routes/__dashboard/analytics'
import { Route as _dashboard_authenticatedRouteImport } from './routes/__dashboard/__authenticated'
import { Route as _dashboardDemoIndexRouteImport } from './routes/__dashboard/demo/index'
import { Route as _dashboardDatabasesIndexRouteImport } from './routes/__dashboard/databases.index'
import { Route as _dashboardDemoOverviewRouteImport } from './routes/__dashboard/demo/overview'
import { Route as _dashboardDemoExplorerRouteImport } from './routes/__dashboard/demo/explorer'
import { Route as _dashboardDemoDangerRouteImport } from './routes/__dashboard/demo/danger'
import { Route as _dashboardDemoConnectRouteImport } from './routes/__dashboard/demo/connect'
import { Route as _dashboardDemoConfigurationRouteImport } from './routes/__dashboard/demo/configuration'
import { Route as _dashboardDemoAnalyticsRouteImport } from './routes/__dashboard/demo/analytics'
import { Route as _dashboard_authenticatedDatabasesDbIdRouteImport } from './routes/__dashboard/__authenticated/databases/$dbId'
import { Route as _dashboard_authenticatedDatabasesDbIdOverviewRouteImport } from './routes/__dashboard/__authenticated/databases/$dbId/overview'
import { Route as _dashboard_authenticatedDatabasesDbIdExplorerRouteImport } from './routes/__dashboard/__authenticated/databases/$dbId/explorer'
import { Route as _dashboard_authenticatedDatabasesDbIdDangerRouteImport } from './routes/__dashboard/__authenticated/databases/$dbId/danger'
import { Route as _dashboard_authenticatedDatabasesDbIdConnectRouteImport } from './routes/__dashboard/__authenticated/databases/$dbId/connect'
import { Route as _dashboard_authenticatedDatabasesDbIdConfigurationRouteImport } from './routes/__dashboard/__authenticated/databases/$dbId/configuration'
import { Route as _dashboard_authenticatedDatabasesDbIdAnalyticsRouteImport } from './routes/__dashboard/__authenticated/databases/$dbId/analytics'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const rootServerRouteImport = createServerRootRoute()

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const _dashboardRoute = _dashboardRouteImport.update({
  id: '/__dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const _dashboardSettingsRoute = _dashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => _dashboardRoute,
} as any)
const _dashboardLogsRoute = _dashboardLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => _dashboardRoute,
} as any)
const _dashboardDemoRoute = _dashboardDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => _dashboardRoute,
} as any)
const _dashboardAnalyticsRoute = _dashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => _dashboardRoute,
} as any)
const _dashboard_authenticatedRoute =
  _dashboard_authenticatedRouteImport.update({
    id: '/__authenticated',
    getParentRoute: () => _dashboardRoute,
  } as any)
const _dashboardDemoIndexRoute = _dashboardDemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _dashboardDemoRoute,
} as any)
const _dashboardDatabasesIndexRoute =
  _dashboardDatabasesIndexRouteImport.update({
    id: '/databases/',
    path: '/databases/',
    getParentRoute: () => _dashboardRoute,
  } as any)
const _dashboardDemoOverviewRoute = _dashboardDemoOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => _dashboardDemoRoute,
} as any)
const _dashboardDemoExplorerRoute = _dashboardDemoExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => _dashboardDemoRoute,
} as any)
const _dashboardDemoDangerRoute = _dashboardDemoDangerRouteImport.update({
  id: '/danger',
  path: '/danger',
  getParentRoute: () => _dashboardDemoRoute,
} as any)
const _dashboardDemoConnectRoute = _dashboardDemoConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => _dashboardDemoRoute,
} as any)
const _dashboardDemoConfigurationRoute =
  _dashboardDemoConfigurationRouteImport.update({
    id: '/configuration',
    path: '/configuration',
    getParentRoute: () => _dashboardDemoRoute,
  } as any)
const _dashboardDemoAnalyticsRoute = _dashboardDemoAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => _dashboardDemoRoute,
} as any)
const _dashboard_authenticatedDatabasesDbIdRoute =
  _dashboard_authenticatedDatabasesDbIdRouteImport.update({
    id: '/databases/$dbId',
    path: '/databases/$dbId',
    getParentRoute: () => _dashboard_authenticatedRoute,
  } as any)
const _dashboard_authenticatedDatabasesDbIdOverviewRoute =
  _dashboard_authenticatedDatabasesDbIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => _dashboard_authenticatedDatabasesDbIdRoute,
  } as any)
const _dashboard_authenticatedDatabasesDbIdExplorerRoute =
  _dashboard_authenticatedDatabasesDbIdExplorerRouteImport.update({
    id: '/explorer',
    path: '/explorer',
    getParentRoute: () => _dashboard_authenticatedDatabasesDbIdRoute,
  } as any)
const _dashboard_authenticatedDatabasesDbIdDangerRoute =
  _dashboard_authenticatedDatabasesDbIdDangerRouteImport.update({
    id: '/danger',
    path: '/danger',
    getParentRoute: () => _dashboard_authenticatedDatabasesDbIdRoute,
  } as any)
const _dashboard_authenticatedDatabasesDbIdConnectRoute =
  _dashboard_authenticatedDatabasesDbIdConnectRouteImport.update({
    id: '/connect',
    path: '/connect',
    getParentRoute: () => _dashboard_authenticatedDatabasesDbIdRoute,
  } as any)
const _dashboard_authenticatedDatabasesDbIdConfigurationRoute =
  _dashboard_authenticatedDatabasesDbIdConfigurationRouteImport.update({
    id: '/configuration',
    path: '/configuration',
    getParentRoute: () => _dashboard_authenticatedDatabasesDbIdRoute,
  } as any)
const _dashboard_authenticatedDatabasesDbIdAnalyticsRoute =
  _dashboard_authenticatedDatabasesDbIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => _dashboard_authenticatedDatabasesDbIdRoute,
  } as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof _dashboardAnalyticsRoute
  '/demo': typeof _dashboardDemoRouteWithChildren
  '/logs': typeof _dashboardLogsRoute
  '/settings': typeof _dashboardSettingsRoute
  '/demo/analytics': typeof _dashboardDemoAnalyticsRoute
  '/demo/configuration': typeof _dashboardDemoConfigurationRoute
  '/demo/connect': typeof _dashboardDemoConnectRoute
  '/demo/danger': typeof _dashboardDemoDangerRoute
  '/demo/explorer': typeof _dashboardDemoExplorerRoute
  '/demo/overview': typeof _dashboardDemoOverviewRoute
  '/databases': typeof _dashboardDatabasesIndexRoute
  '/demo/': typeof _dashboardDemoIndexRoute
  '/databases/$dbId': typeof _dashboard_authenticatedDatabasesDbIdRouteWithChildren
  '/databases/$dbId/analytics': typeof _dashboard_authenticatedDatabasesDbIdAnalyticsRoute
  '/databases/$dbId/configuration': typeof _dashboard_authenticatedDatabasesDbIdConfigurationRoute
  '/databases/$dbId/connect': typeof _dashboard_authenticatedDatabasesDbIdConnectRoute
  '/databases/$dbId/danger': typeof _dashboard_authenticatedDatabasesDbIdDangerRoute
  '/databases/$dbId/explorer': typeof _dashboard_authenticatedDatabasesDbIdExplorerRoute
  '/databases/$dbId/overview': typeof _dashboard_authenticatedDatabasesDbIdOverviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof _dashboardAnalyticsRoute
  '/logs': typeof _dashboardLogsRoute
  '/settings': typeof _dashboardSettingsRoute
  '/demo/analytics': typeof _dashboardDemoAnalyticsRoute
  '/demo/configuration': typeof _dashboardDemoConfigurationRoute
  '/demo/connect': typeof _dashboardDemoConnectRoute
  '/demo/danger': typeof _dashboardDemoDangerRoute
  '/demo/explorer': typeof _dashboardDemoExplorerRoute
  '/demo/overview': typeof _dashboardDemoOverviewRoute
  '/databases': typeof _dashboardDatabasesIndexRoute
  '/demo': typeof _dashboardDemoIndexRoute
  '/databases/$dbId': typeof _dashboard_authenticatedDatabasesDbIdRouteWithChildren
  '/databases/$dbId/analytics': typeof _dashboard_authenticatedDatabasesDbIdAnalyticsRoute
  '/databases/$dbId/configuration': typeof _dashboard_authenticatedDatabasesDbIdConfigurationRoute
  '/databases/$dbId/connect': typeof _dashboard_authenticatedDatabasesDbIdConnectRoute
  '/databases/$dbId/danger': typeof _dashboard_authenticatedDatabasesDbIdDangerRoute
  '/databases/$dbId/explorer': typeof _dashboard_authenticatedDatabasesDbIdExplorerRoute
  '/databases/$dbId/overview': typeof _dashboard_authenticatedDatabasesDbIdOverviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/__dashboard': typeof _dashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/__dashboard/__authenticated': typeof _dashboard_authenticatedRouteWithChildren
  '/__dashboard/analytics': typeof _dashboardAnalyticsRoute
  '/__dashboard/demo': typeof _dashboardDemoRouteWithChildren
  '/__dashboard/logs': typeof _dashboardLogsRoute
  '/__dashboard/settings': typeof _dashboardSettingsRoute
  '/__dashboard/demo/analytics': typeof _dashboardDemoAnalyticsRoute
  '/__dashboard/demo/configuration': typeof _dashboardDemoConfigurationRoute
  '/__dashboard/demo/connect': typeof _dashboardDemoConnectRoute
  '/__dashboard/demo/danger': typeof _dashboardDemoDangerRoute
  '/__dashboard/demo/explorer': typeof _dashboardDemoExplorerRoute
  '/__dashboard/demo/overview': typeof _dashboardDemoOverviewRoute
  '/__dashboard/databases/': typeof _dashboardDatabasesIndexRoute
  '/__dashboard/demo/': typeof _dashboardDemoIndexRoute
  '/__dashboard/__authenticated/databases/$dbId': typeof _dashboard_authenticatedDatabasesDbIdRouteWithChildren
  '/__dashboard/__authenticated/databases/$dbId/analytics': typeof _dashboard_authenticatedDatabasesDbIdAnalyticsRoute
  '/__dashboard/__authenticated/databases/$dbId/configuration': typeof _dashboard_authenticatedDatabasesDbIdConfigurationRoute
  '/__dashboard/__authenticated/databases/$dbId/connect': typeof _dashboard_authenticatedDatabasesDbIdConnectRoute
  '/__dashboard/__authenticated/databases/$dbId/danger': typeof _dashboard_authenticatedDatabasesDbIdDangerRoute
  '/__dashboard/__authenticated/databases/$dbId/explorer': typeof _dashboard_authenticatedDatabasesDbIdExplorerRoute
  '/__dashboard/__authenticated/databases/$dbId/overview': typeof _dashboard_authenticatedDatabasesDbIdOverviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/demo'
    | '/logs'
    | '/settings'
    | '/demo/analytics'
    | '/demo/configuration'
    | '/demo/connect'
    | '/demo/danger'
    | '/demo/explorer'
    | '/demo/overview'
    | '/databases'
    | '/demo/'
    | '/databases/$dbId'
    | '/databases/$dbId/analytics'
    | '/databases/$dbId/configuration'
    | '/databases/$dbId/connect'
    | '/databases/$dbId/danger'
    | '/databases/$dbId/explorer'
    | '/databases/$dbId/overview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/analytics'
    | '/logs'
    | '/settings'
    | '/demo/analytics'
    | '/demo/configuration'
    | '/demo/connect'
    | '/demo/danger'
    | '/demo/explorer'
    | '/demo/overview'
    | '/databases'
    | '/demo'
    | '/databases/$dbId'
    | '/databases/$dbId/analytics'
    | '/databases/$dbId/configuration'
    | '/databases/$dbId/connect'
    | '/databases/$dbId/danger'
    | '/databases/$dbId/explorer'
    | '/databases/$dbId/overview'
  id:
    | '__root__'
    | '/'
    | '/__dashboard'
    | '/login'
    | '/__dashboard/__authenticated'
    | '/__dashboard/analytics'
    | '/__dashboard/demo'
    | '/__dashboard/logs'
    | '/__dashboard/settings'
    | '/__dashboard/demo/analytics'
    | '/__dashboard/demo/configuration'
    | '/__dashboard/demo/connect'
    | '/__dashboard/demo/danger'
    | '/__dashboard/demo/explorer'
    | '/__dashboard/demo/overview'
    | '/__dashboard/databases/'
    | '/__dashboard/demo/'
    | '/__dashboard/__authenticated/databases/$dbId'
    | '/__dashboard/__authenticated/databases/$dbId/analytics'
    | '/__dashboard/__authenticated/databases/$dbId/configuration'
    | '/__dashboard/__authenticated/databases/$dbId/connect'
    | '/__dashboard/__authenticated/databases/$dbId/danger'
    | '/__dashboard/__authenticated/databases/$dbId/explorer'
    | '/__dashboard/__authenticated/databases/$dbId/overview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  _dashboardRoute: typeof _dashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}
export interface FileServerRoutesByFullPath {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/auth/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/auth/$'
  id: '__root__' | '/api/auth/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__dashboard': {
      id: '/__dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _dashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__dashboard/settings': {
      id: '/__dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof _dashboardSettingsRouteImport
      parentRoute: typeof _dashboardRoute
    }
    '/__dashboard/logs': {
      id: '/__dashboard/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof _dashboardLogsRouteImport
      parentRoute: typeof _dashboardRoute
    }
    '/__dashboard/demo': {
      id: '/__dashboard/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof _dashboardDemoRouteImport
      parentRoute: typeof _dashboardRoute
    }
    '/__dashboard/analytics': {
      id: '/__dashboard/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof _dashboardAnalyticsRouteImport
      parentRoute: typeof _dashboardRoute
    }
    '/__dashboard/__authenticated': {
      id: '/__dashboard/__authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _dashboard_authenticatedRouteImport
      parentRoute: typeof _dashboardRoute
    }
    '/__dashboard/demo/': {
      id: '/__dashboard/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof _dashboardDemoIndexRouteImport
      parentRoute: typeof _dashboardDemoRoute
    }
    '/__dashboard/databases/': {
      id: '/__dashboard/databases/'
      path: '/databases'
      fullPath: '/databases'
      preLoaderRoute: typeof _dashboardDatabasesIndexRouteImport
      parentRoute: typeof _dashboardRoute
    }
    '/__dashboard/demo/overview': {
      id: '/__dashboard/demo/overview'
      path: '/overview'
      fullPath: '/demo/overview'
      preLoaderRoute: typeof _dashboardDemoOverviewRouteImport
      parentRoute: typeof _dashboardDemoRoute
    }
    '/__dashboard/demo/explorer': {
      id: '/__dashboard/demo/explorer'
      path: '/explorer'
      fullPath: '/demo/explorer'
      preLoaderRoute: typeof _dashboardDemoExplorerRouteImport
      parentRoute: typeof _dashboardDemoRoute
    }
    '/__dashboard/demo/danger': {
      id: '/__dashboard/demo/danger'
      path: '/danger'
      fullPath: '/demo/danger'
      preLoaderRoute: typeof _dashboardDemoDangerRouteImport
      parentRoute: typeof _dashboardDemoRoute
    }
    '/__dashboard/demo/connect': {
      id: '/__dashboard/demo/connect'
      path: '/connect'
      fullPath: '/demo/connect'
      preLoaderRoute: typeof _dashboardDemoConnectRouteImport
      parentRoute: typeof _dashboardDemoRoute
    }
    '/__dashboard/demo/configuration': {
      id: '/__dashboard/demo/configuration'
      path: '/configuration'
      fullPath: '/demo/configuration'
      preLoaderRoute: typeof _dashboardDemoConfigurationRouteImport
      parentRoute: typeof _dashboardDemoRoute
    }
    '/__dashboard/demo/analytics': {
      id: '/__dashboard/demo/analytics'
      path: '/analytics'
      fullPath: '/demo/analytics'
      preLoaderRoute: typeof _dashboardDemoAnalyticsRouteImport
      parentRoute: typeof _dashboardDemoRoute
    }
    '/__dashboard/__authenticated/databases/$dbId': {
      id: '/__dashboard/__authenticated/databases/$dbId'
      path: '/databases/$dbId'
      fullPath: '/databases/$dbId'
      preLoaderRoute: typeof _dashboard_authenticatedDatabasesDbIdRouteImport
      parentRoute: typeof _dashboard_authenticatedRoute
    }
    '/__dashboard/__authenticated/databases/$dbId/overview': {
      id: '/__dashboard/__authenticated/databases/$dbId/overview'
      path: '/overview'
      fullPath: '/databases/$dbId/overview'
      preLoaderRoute: typeof _dashboard_authenticatedDatabasesDbIdOverviewRouteImport
      parentRoute: typeof _dashboard_authenticatedDatabasesDbIdRoute
    }
    '/__dashboard/__authenticated/databases/$dbId/explorer': {
      id: '/__dashboard/__authenticated/databases/$dbId/explorer'
      path: '/explorer'
      fullPath: '/databases/$dbId/explorer'
      preLoaderRoute: typeof _dashboard_authenticatedDatabasesDbIdExplorerRouteImport
      parentRoute: typeof _dashboard_authenticatedDatabasesDbIdRoute
    }
    '/__dashboard/__authenticated/databases/$dbId/danger': {
      id: '/__dashboard/__authenticated/databases/$dbId/danger'
      path: '/danger'
      fullPath: '/databases/$dbId/danger'
      preLoaderRoute: typeof _dashboard_authenticatedDatabasesDbIdDangerRouteImport
      parentRoute: typeof _dashboard_authenticatedDatabasesDbIdRoute
    }
    '/__dashboard/__authenticated/databases/$dbId/connect': {
      id: '/__dashboard/__authenticated/databases/$dbId/connect'
      path: '/connect'
      fullPath: '/databases/$dbId/connect'
      preLoaderRoute: typeof _dashboard_authenticatedDatabasesDbIdConnectRouteImport
      parentRoute: typeof _dashboard_authenticatedDatabasesDbIdRoute
    }
    '/__dashboard/__authenticated/databases/$dbId/configuration': {
      id: '/__dashboard/__authenticated/databases/$dbId/configuration'
      path: '/configuration'
      fullPath: '/databases/$dbId/configuration'
      preLoaderRoute: typeof _dashboard_authenticatedDatabasesDbIdConfigurationRouteImport
      parentRoute: typeof _dashboard_authenticatedDatabasesDbIdRoute
    }
    '/__dashboard/__authenticated/databases/$dbId/analytics': {
      id: '/__dashboard/__authenticated/databases/$dbId/analytics'
      path: '/analytics'
      fullPath: '/databases/$dbId/analytics'
      preLoaderRoute: typeof _dashboard_authenticatedDatabasesDbIdAnalyticsRouteImport
      parentRoute: typeof _dashboard_authenticatedDatabasesDbIdRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface _dashboard_authenticatedDatabasesDbIdRouteChildren {
  _dashboard_authenticatedDatabasesDbIdAnalyticsRoute: typeof _dashboard_authenticatedDatabasesDbIdAnalyticsRoute
  _dashboard_authenticatedDatabasesDbIdConfigurationRoute: typeof _dashboard_authenticatedDatabasesDbIdConfigurationRoute
  _dashboard_authenticatedDatabasesDbIdConnectRoute: typeof _dashboard_authenticatedDatabasesDbIdConnectRoute
  _dashboard_authenticatedDatabasesDbIdDangerRoute: typeof _dashboard_authenticatedDatabasesDbIdDangerRoute
  _dashboard_authenticatedDatabasesDbIdExplorerRoute: typeof _dashboard_authenticatedDatabasesDbIdExplorerRoute
  _dashboard_authenticatedDatabasesDbIdOverviewRoute: typeof _dashboard_authenticatedDatabasesDbIdOverviewRoute
}

const _dashboard_authenticatedDatabasesDbIdRouteChildren: _dashboard_authenticatedDatabasesDbIdRouteChildren =
  {
    _dashboard_authenticatedDatabasesDbIdAnalyticsRoute:
      _dashboard_authenticatedDatabasesDbIdAnalyticsRoute,
    _dashboard_authenticatedDatabasesDbIdConfigurationRoute:
      _dashboard_authenticatedDatabasesDbIdConfigurationRoute,
    _dashboard_authenticatedDatabasesDbIdConnectRoute:
      _dashboard_authenticatedDatabasesDbIdConnectRoute,
    _dashboard_authenticatedDatabasesDbIdDangerRoute:
      _dashboard_authenticatedDatabasesDbIdDangerRoute,
    _dashboard_authenticatedDatabasesDbIdExplorerRoute:
      _dashboard_authenticatedDatabasesDbIdExplorerRoute,
    _dashboard_authenticatedDatabasesDbIdOverviewRoute:
      _dashboard_authenticatedDatabasesDbIdOverviewRoute,
  }

const _dashboard_authenticatedDatabasesDbIdRouteWithChildren =
  _dashboard_authenticatedDatabasesDbIdRoute._addFileChildren(
    _dashboard_authenticatedDatabasesDbIdRouteChildren,
  )

interface _dashboard_authenticatedRouteChildren {
  _dashboard_authenticatedDatabasesDbIdRoute: typeof _dashboard_authenticatedDatabasesDbIdRouteWithChildren
}

const _dashboard_authenticatedRouteChildren: _dashboard_authenticatedRouteChildren =
  {
    _dashboard_authenticatedDatabasesDbIdRoute:
      _dashboard_authenticatedDatabasesDbIdRouteWithChildren,
  }

const _dashboard_authenticatedRouteWithChildren =
  _dashboard_authenticatedRoute._addFileChildren(
    _dashboard_authenticatedRouteChildren,
  )

interface _dashboardDemoRouteChildren {
  _dashboardDemoAnalyticsRoute: typeof _dashboardDemoAnalyticsRoute
  _dashboardDemoConfigurationRoute: typeof _dashboardDemoConfigurationRoute
  _dashboardDemoConnectRoute: typeof _dashboardDemoConnectRoute
  _dashboardDemoDangerRoute: typeof _dashboardDemoDangerRoute
  _dashboardDemoExplorerRoute: typeof _dashboardDemoExplorerRoute
  _dashboardDemoOverviewRoute: typeof _dashboardDemoOverviewRoute
  _dashboardDemoIndexRoute: typeof _dashboardDemoIndexRoute
}

const _dashboardDemoRouteChildren: _dashboardDemoRouteChildren = {
  _dashboardDemoAnalyticsRoute: _dashboardDemoAnalyticsRoute,
  _dashboardDemoConfigurationRoute: _dashboardDemoConfigurationRoute,
  _dashboardDemoConnectRoute: _dashboardDemoConnectRoute,
  _dashboardDemoDangerRoute: _dashboardDemoDangerRoute,
  _dashboardDemoExplorerRoute: _dashboardDemoExplorerRoute,
  _dashboardDemoOverviewRoute: _dashboardDemoOverviewRoute,
  _dashboardDemoIndexRoute: _dashboardDemoIndexRoute,
}

const _dashboardDemoRouteWithChildren = _dashboardDemoRoute._addFileChildren(
  _dashboardDemoRouteChildren,
)

interface _dashboardRouteChildren {
  _dashboard_authenticatedRoute: typeof _dashboard_authenticatedRouteWithChildren
  _dashboardAnalyticsRoute: typeof _dashboardAnalyticsRoute
  _dashboardDemoRoute: typeof _dashboardDemoRouteWithChildren
  _dashboardLogsRoute: typeof _dashboardLogsRoute
  _dashboardSettingsRoute: typeof _dashboardSettingsRoute
  _dashboardDatabasesIndexRoute: typeof _dashboardDatabasesIndexRoute
}

const _dashboardRouteChildren: _dashboardRouteChildren = {
  _dashboard_authenticatedRoute: _dashboard_authenticatedRouteWithChildren,
  _dashboardAnalyticsRoute: _dashboardAnalyticsRoute,
  _dashboardDemoRoute: _dashboardDemoRouteWithChildren,
  _dashboardLogsRoute: _dashboardLogsRoute,
  _dashboardSettingsRoute: _dashboardSettingsRoute,
  _dashboardDatabasesIndexRoute: _dashboardDatabasesIndexRoute,
}

const _dashboardRouteWithChildren = _dashboardRoute._addFileChildren(
  _dashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  _dashboardRoute: _dashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
